services:
  - type: web
    name: Placars
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 manage.py runserver"
    envVars:
      - key: 
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4