# Generated by Django 4.2.7 on 2023-12-28 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "company_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                ("application_count", models.IntegerField()),
                ("salary", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "job_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="findJobApi.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("mail", models.EmailField(max_length=254, unique=True)),
                (
                    "person_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("Erkek", "Erkek"),
                            ("Kadin", "Kadin"),
                            ("DIGER", "Diger"),
                        ],
                        max_length=255,
                    ),
                ),
                ("user_password", models.CharField(max_length=255)),
                ("profile_img_url", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                (
                    "user_post_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("user_post_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="findJobApi.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "job_application_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="findJobApi.company",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="findJobApi.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="findJobApi.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPost",
            fields=[
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=1000)),
                (
                    "company_post_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("company_post_date", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="findJobApi.company",
                    ),
                ),
            ],
        ),
    ]
